### ISSUE TITLE
Why in DDIM not have p_x()

### ISSUE THREAD

**Issue by CiRA-AMI** [GlassyWing/TorchDiffusion#1]
Dear GlassyWing
Your work is amazing that can creat diffusion in libtoch c++
I want to ask you about In DDIM

in train.cpp
std::tie(noise_images, steps, noise) = sampler->p_x(data);

but in ddim.cpp doesn't implement p_x() function ?
May I ask you the reason ?
Best regard

**Comment by GlassyWing** [comment]
> Dear GlassyWing Your work is amazing that can creat diffusion in libtoch c++ I want to ask you about In DDIM
> 
> in train.cpp std::tie(noise_images, steps, noise) = sampler->p_x(data);
> 
> but in ddim.cpp doesn't implement p_x() function ? May I ask you the reason ? Best regard

This is because DDIM inherits DDPM, and their training processes are identical, except for different sampling methods.

**Comment by CiRA-AMI** [comment]
Thank you.
